baseURL = "https://claudioonohara.github.io/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
title = "Projetos"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
author = "Claudio Onohara"
description = "Claudio Onohara"
profilePicture = "images/claudio_avatar_github.jpg"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Projetos"
  weight = 200
  identifier = "posts"
  url = "/post/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ctocto/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/claudioonohara/"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
